import { Dosis } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const dosis = Dosis({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"],
});

export const metadata = {
  title: "Exanime || Allan🔥",
  description: "Generated by Allan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {" "}
        <link rel="icon" href="/icon.png"></link>
      </Head>
      <body className={`${dosis.className} bg-color-dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
