import { Dosis } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const dosis = Dosis({ subsets: ["latin"], weight:['200', '400', '600', '800'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dosis.className} bg-color-dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
